trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Build"
  jobs:
    - job: BuildJob
      steps:
        - script: echo "Build started"
        - script: echo "Complile started"
        - script: echo "Build completed"
